# Taken and modified from https://github.com/biocore/burrito
# Check on http://lint.travis-ci.org/ after modifying it!
language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install nose pep8 flake8 coveralls
script:
  - nosetests --with-coverage
  - pep8 qiime_plugin framework
  - flake8 qiime_plugin framework
after_success:
  - coveralls
